import{a as h,S as L,i as c}from"./assets/vendor-Epugobq5.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const r of document.querySelectorAll('link[rel="modulepreload"]'))s(r);new MutationObserver(r=>{for(const o of r)if(o.type==="childList")for(const l of o.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&s(l)}).observe(document,{childList:!0,subtree:!0});function a(r){const o={};return r.integrity&&(o.integrity=r.integrity),r.referrerPolicy&&(o.referrerPolicy=r.referrerPolicy),r.crossOrigin==="use-credentials"?o.credentials="include":r.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function s(r){if(r.ep)return;r.ep=!0;const o=a(r);fetch(r.href,o)}})();const w="49480217-2522e2603317fe0a16a9eaac0",q="https://pixabay.com/api/";let g=1;const v=15;function P(){g=1}function S(){g+=1}async function b(t){const e={key:w,q:t,image_type:"photo",orientation:"horizontal",safesearch:"true",page:g,per_page:v};try{return(await h.get(q,{params:e})).data}catch(a){throw console.error("Fetch images error:",a.message),a}}function p(){const t=document.querySelector(".gallery");t.innerHTML=""}function I(t){const e=document.querySelector(".gallery"),a=t.map(s=>`
    <li class="gallery-item">
      <a href="${s.largeImageURL}">
        <img class="gallery-image" src="${s.webformatURL}" alt="${s.tags}" />
        <div class="info">
          <p>Likes ${s.likes}</p>
          <p>Views ${s.views}</p>
          <p>Comments ${s.comments}</p>
          <p>Downloads ${s.downloads}</p>
        </div>
      </a>
    </li>
  `).join("");e.insertAdjacentHTML("beforeend",a)}const m=document.querySelector(".form"),$=document.querySelector(".loader"),n=document.querySelector(".load-more");let f="",d=0,i=0;const O=new L(".gallery a",{captionsData:"alt",captionDelay:250});m.addEventListener("submit",async t=>{t.preventDefault();const e=t.target.elements.searchQuery.value.trim();if(!e)return c.error({message:"Please enter a search query!",position:"topLeft"});e!==f&&(P(),p(),n.classList.add("hidden"),f=e,i=0),await y(),m.reset()});n.addEventListener("click",async()=>{S(),await y(!0)});async function y(t=!1){t||(p(),i=0,d=0,n.classList.add("hidden")),u(!0);try{const e=await b(f);if(u(!1),e.hits.length===0&&i===0)return n.classList.add("hidden"),c.warning({message:"Sorry, there are no images matching your search query. Please try again!",position:"topLeft"});I(e.hits),O.refresh(),i+=e.hits.length,d=e.totalHits,i<d?n.classList.remove("hidden"):(n.classList.add("hidden"),c.info({message:"We're sorry, but you've reached the end of search results.",position:"topLeft"})),t&&A()}catch{u(!1),c.error({message:"An error occurred. Please try again.",position:"topLeft"})}}function u(t){$.classList.toggle("hidden",!t),n.classList.toggle("hidden",t)}function A(){const t=document.querySelector(".gallery-item");if(t){const e=t.getBoundingClientRect().height;window.scrollBy({top:e*2,behavior:"smooth"})}}
//# sourceMappingURL=index.js.map
